### ISSUE TITLE
"_OBJC_CLASS_$_PcmPlayer", referenced from:

### ISSUE THREAD

**Issue by JasonLxj** [PEPDigitalPublishing/PEPReaderSDK#1]
pod那里少了一行 
 pod 'PEPiFlyMSC', :git => 'https://github.com/PEPDigitalPublishing/PEPiFlyMSC.git'

**Comment by RavenKite** [comment]
已更新[README.md](https://github.com/PEPDigitalPublishing/PEPReaderSDK/blob/master/README.md)
