### ISSUE TITLE
你好。关于语文课文点读实现思路的问题

### ISSUE THREAD

**Issue by Wxm510846302** [PEPDigitalPublishing/PEPReaderSDK#3]
我有幸看到人教点读app，然后有一些疑问。在打开课本后，应该就是下载pdf格式的文档和所对应的音频吧？（如果没有音频，那应该就是文字转换的语音吧？）然后pdf加载出来后，课文上的点读区域是如何绘制上去的呢？每页的点读区域都不相同，是不是根据后台返回的数据然后ios端再用原生绘制的呢？还是说使用web等其他方案？希望不吝赐教！谢谢。

**Comment by hanLemon** [comment]
对的，打开课本后加载的就是之前下载的pdf和音频
点读区域是我们针对pdf加工处理的，在pdf上制作的锚点，锚点上有该资源对应的详细信息
选读框是pdf绘制层的一种样式，也是可以iOS原生绘制实现的
